version: '3.9'

services:
  db:
    image: postgres:16.3
    container_name: rails-example-db
    profiles:
      - dev
    environment:
      - POSTGRES_USER: rails-example 
      - POSTGRES_PASSWORD: rails-example
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data
    ports:
      - 5435:5432
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: